export const FORM_ELEMENT_OPTIONS = [
    { value: 'input', label: '输入框', short: 'i' },
    { value: 'hidden', label: '隐藏框', short: 'h' },
    { value: 'number', label: '数字框', short: 'n' },
    { value: 'textarea', label: '文本框', short: 't' },
    { value: 'password', label: '密码框', short: 'p' },
    { value: 'mobile', label: '手机输入框', short: 'm' },
    { value: 'email', label: '邮箱输入框', short: 'e' },
    { value: 'select', label: '下拉框', short: 's' },
    { value: 'select-tree', label: '下拉树', short: 'st' },
    { value: 'checkbox', label: '复选框', short: 'c' },
    { value: 'checkbox-group', label: '复选框组', short: 'cg' },
    { value: 'radio', label: '单选框', short: 'r' },
    { value: 'radio-group', label: '单选框组', short: 'rg' },
    { value: 'radio-button', label: '单选按钮组', short: 'rb' },
    { value: 'switch', label: '切换按钮', short: 'sw' },
    { value: 'date', label: '日期选择框', short: 'd' },
    { value: 'time', label: '时间选择框', short: 'ti' },
    { value: 'moth', label: '月份选择框', short: 'mo' },
    { value: 'date-time', label: '日期+时间选择框', short: 'dt' },
    { value: 'date-range', label: '日期区间选择框', short: 'dr' },
    { value: 'cascader', label: '级联下拉框', short: 'ca' },
    { value: 'transfer', label: '穿梭框', short: 'tr' },
];

// 后端数据类型，以java为准，如果后端是其他类型，编写模板时，基于java再次转换
export const DATA_TYPE_OPTIONS = [
    { value: 'String', label: 'String' },
    { value: 'int', label: 'int' },
    { value: 'long', label: 'long' },
    { value: 'boolean', label: 'boolean' },
    { value: 'BigInteger', label: 'BigInteger' },
    { value: 'float', label: 'float' },
    { value: 'double', label: 'double' },
    { value: 'BigDecimal', label: 'BigDecimal' },
    { value: 'Date', label: 'Date' },
    { value: 'Time', label: 'Time' },
    { value: 'Timestamp', label: 'Timestamp' },
];

export const VALIDATE_OPTIONS = [
    { value: 'required', label: '必填' },
    { value: 'noSpace', label: '无空格' },
    { value: 'unique', label: '不可重复' },
    { value: 'mobile', label: '手机号' },
    { value: 'landLine', label: '座机号' },
    { value: 'email', label: '邮箱' },
    { value: 'cardNumber', label: '身份证号' },
    { value: 'qq', label: 'qq号' },
    { value: 'ip', label: 'IP地址' },
    { value: 'port', label: '端口号' },
    { value: 'positiveInteger', label: '正整数' },
    { value: 'numberWithTwoDecimal', label: '数字、保存两位小数' },
];
